spring.application.name=analyzer

spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://kora-one-vault.vault.azure.net/
gemini.api.key=${gemini-api-key}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent