spring.application.name=analyzer

spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://kora-one-vault.vault.azure.net/

gemini.api.key=${gemini-api-key}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${spring-data-redis-password:}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}